USE [master]
GO

/****** Object:  Database [HealthCare]    Script Date: 09-06-2025 00:38:25 ******/
CREATE DATABASE [HealthCare]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'HealthCare', FILENAME = N'C:\Users\Sakthisivam\HealthCare.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'HealthCare_log', FILENAME = N'C:\Users\Sakthisivam\HealthCare_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [HealthCare].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [HealthCare] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [HealthCare] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [HealthCare] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [HealthCare] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [HealthCare] SET ARITHABORT OFF 
GO

ALTER DATABASE [HealthCare] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [HealthCare] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [HealthCare] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [HealthCare] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [HealthCare] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [HealthCare] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [HealthCare] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [HealthCare] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [HealthCare] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [HealthCare] SET  ENABLE_BROKER 
GO

ALTER DATABASE [HealthCare] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [HealthCare] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [HealthCare] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [HealthCare] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [HealthCare] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [HealthCare] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [HealthCare] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [HealthCare] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [HealthCare] SET  MULTI_USER 
GO

ALTER DATABASE [HealthCare] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [HealthCare] SET DB_CHAINING OFF 
GO

ALTER DATABASE [HealthCare] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [HealthCare] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [HealthCare] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [HealthCare] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [HealthCare] SET QUERY_STORE = OFF
GO

ALTER DATABASE [HealthCare] SET  READ_WRITE 
GO

